### ISSUE TITLE
エントリー受付のキャンセルができない

### ISSUE THREAD

**Issue by hidehara** [fkpc/kanirobocon-system#12]
[エントリー受付](http://[::]:8000/menu.html) で 「エントリー」ボタンを押して赤色。

その後、再度「エントリー」ボタンを押して、エントリー受付をキャンセルして白色に戻せるが、再度リロードすると、赤色に戻り、キャンセルが完了されてないことがわかる。

**Comment by hidehara** [comment]
register.csv を開きながら観察した結果：

- 受付時：MiniDB.set -> 1行増える
- キャンセル時：MiniDB.remove -> 行数に変化がない（削除されない）

どちらも endpoint : /api/kanirobocon/ にGETパラメーター組合わせてたたいてるので、API側での対応が必要？

**Comment by taisukef** [comment]
ありがとう！
MiniDBのremoveに対応するコードがなかったことが原因でした

こちらで修正完了
https://github.com/fkpc/kanirobocon-system/commit/2a28dba52d3bbd031340c4d2ef13752c92c33c7d

**Comment by hidehara** [comment]
minidb.js って２ファイルあるのね！

修正ありがとうー

**Comment by taisukef** [comment]
MiniDB.js が、フロント用のライブラリで、minidb.js がバックエンドでの処理用ライブラリ
