### ISSUE TITLE
エントリー部門の決勝トーナメント表の最終対戦が表示されない

### ISSUE THREAD

**Issue by hidehara** [fkpc/kanirobocon-system#9]
決勝トーナメント表の決勝が表示されないようです。

<img width="565" alt="image" src="https://user-images.githubusercontent.com/4308281/201506382-98f2498f-b4ff-4856-ade9-ccb5b937715a.png">

**Comment by taisukef** [comment]
勝者が決まってないからではなく？？

**Comment by hidehara** [comment]
そうだね。

図の１８ように、勝者が決まってないときには、
　試合１２の勝者　ｘ　試合１１の勝者
とでてた。（歩行側でいれたダミーデーター　４名では正しい）

エントリーは、決勝進出８名で組んでて。
今回の期待値は、次の２つが最後にある。だったのだけども表示されずだったんです。

* 19 : 試合17の勝者　ｘ　試合16の勝者
* 20 : 試合16の勝者　ｘ　試合17の勝者

**Comment by taisukef** [comment]
なるほど
決勝戦の対戦表がないってことか
それはおかしい・・・

**Comment by hidehara** [comment]
かにロボのテストデータだと、再現しませんでした。 > エントリー x8 , 歩行 x8。
それぞれの決勝出場者数が違うとでるかも？

<img width="560" alt="image" src="https://user-images.githubusercontent.com/4308281/202124947-c98515b8-3540-462f-995b-004a087b9792.png">

**Comment by hidehara** [comment]
Reproduced ! 

決勝エントリー数が少ない方に引きづられるもよう。

`	static getNumberOfMatch(category) {
		return category == "T" ? 8 : 4; // 2021 両方8
	}`

<img width="545" alt="image" src="https://user-images.githubusercontent.com/4308281/202125310-63d6dc7e-dcd6-43ab-b725-4095b68826af.png">
